//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Electronics_Showroom
{


    public partial class Logout
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Online_Electronics_Showroom.SiteMaster Master
        {
            get
            {
                return ((Online_Electronics_Showroom.SiteMaster)(base.Master));
            }
        }
    }
}
